### ISSUE TITLE
Combine Python and R repos

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/dsci-100-student#50]
If it works for the server side of things, I think it would be handy to merge the R and Py repos. That way we don't need to keep track of updates to the shared admin files (readme, faq, etc) in two different repos. I made the admin files language-agnostic in https://github.com/UBC-DSCI/dsci-100-student-python/pull/12

 For the materials and slides folders we could have `R` and `Py` subfolders or rename the main folders with an `-r` or `-py` suffix, whatever works best for the server. This will require changing some links around so I don't think we should do it this year, but for next year when we have more time I think this would be an improvement.

**Comment by trevorcampbell** [comment]
It should work fine on the server side. We should indeed merge these.

**Comment by joelostblom** [comment]
Great, let's schedule that as something we do for next summer then. Hopefully this issue is visible enough that the winter instructors remember to make the updates in one file.

**Comment by joelostblom** [comment]
Just saw you comment on the other PR about archiving the python repo already this year. I will go ahead and get started on that

**Comment by trevorcampbell** [comment]
yeah, let's just do it now -- it's not a huge change and i think rudaux can handle it
